# ============================================================
# R/introduction.R — DamPlan landing page
# ============================================================

introduction_ui <- function(id) {
  ns <- NS(id)

  tags$div(
    class = "intro-page",

    tags$div(
      class = "intro-grid",

      # ---- LEFT COLUMN ----
      tags$div(
        class = "intro-left",

        tags$div(
          class = "intro-brand-block",
          tags$h1(
            class = "intro-brand-title",
            tags$span(class = "brand-dam-lg", "Dam"),
            tags$span(class = "brand-plan-lg", "Plan")
          ),
          tags$p(
            class = "intro-tagline",
            "An interactive dashboard for identifying low-impact hydropower
             opportunities that support a net-zero future while preserving
             the world's remaining free-flowing rivers."
          ),
          tags$p(
            class = "intro-audience",
            "For water resource managers, energy planners, researchers, and academics."
          )
        ),

        # Partners
        tags$div(
          class = "intro-meta-block",
          tags$p(class = "intro-meta-label", "Partners"),
          tags$p(class = "intro-meta-body",
            tags$a("World Wildlife Fund (WWF)",
                   href = "https://wwf.panda.org/",
                   target = "_blank", class = "intro-link")
          ),
          tags$p(class = "intro-meta-body",
            tags$a("Schmitt Lab for River System Science and Sustainability",
                   href = "https://www.riversystem.science/",
                   target = "_blank", class = "intro-link")
          )
        ),

        # Developers
        tags$div(
          class = "intro-meta-block",
          tags$p(class = "intro-meta-label", "Developed by"),
          tags$p(class = "intro-meta-body",
            "Aakriti Poudel · Leela Dixit · Megan Hessel · Lucian Scher"
          ),
          tags$p(class = "intro-meta-body",
            tags$a("Bren School of Environmental Science & Management",
                   href = "https://bren.ucsb.edu",
                   target = "_blank", class = "intro-link"),
            ", University of California, Santa Barbara"
          )
        )
      ),

      # ---- RIGHT COLUMN ----
      tags$div(
        class = "intro-right",

        tags$div(
          class = "intro-card",
          tags$h2(class = "intro-card-title", "About"),
          tags$p(class = "intro-card-body",
            "DamPlan is an interactive dashboard for exploring the suitability of
             future hydropower dam sites worldwide. Global decarbonization demands
             a major expansion of renewable energy, including hydropower, but not
             all dam sites are equal. A dam built within an existing cascade has
             far less environmental impact than one placed on a free-flowing river
             that has never been dammed. DamPlan makes this distinction visible
             and actionable."
          ),
          tags$p(class = "intro-card-body",
            "The dashboard displays over 3,700 planned dam sites, each assigned a
             sustainability suitability score generated by a geospatial river
             network analysis model developed in collaboration with the World
             Wildlife Fund. The model evaluates each site's position within its
             river network, proximity to protected areas, and relationship to
             existing upstream and downstream infrastructure, ranked from lowest
             to highest environmental impact."
          )
        ),

        tags$div(
          class = "intro-card",
          tags$h2(class = "intro-card-title", "How to Use"),
          tags$p(class = "intro-card-body",
            "Filter dam sites by river basin, river ID, or river network. For
             each dam, the interactive map displays its connectivity category,
             suitability score, installed capacity, and any fatal flaw indicators."
          )
        )
      )
    ),

    # ---- Footer with GitHub icon ----
    tags$div(
      class = "intro-footer",
      "© 2026 NetZeroHydro · Bren School of Environmental Science & Management · UC Santa Barbara",
      tags$a(
        href   = "https://github.com/NetZeroHydro",
        target = "_blank",
        class  = "intro-github-link",
        tags$i(class = "fab fa-github intro-github-icon")
      )
    )
  )
}

introduction_server <- function(id) {
  moduleServer(id, function(input, output, session) {})
}
